const WorkshopContent = [
    {
        ID:1,
        Name:"Brainwave Robotics Workshop 1",
        About:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis aperiam aut dolorem repellat cum totam architecto. Quo ipsum, excepturi voluptas debitis eos inventore fuga reiciendis illo asperiores quasi tenetur earum tempore placeat odit repellendus rerum eius. Eum veniam ipsum voluptate ea minima porro vitae numquam minus error delectus tenetur voluptatem nobis, doloribus inventore eos debitis eligendi dolorum obcaecati ipsam maxime! Ipsum molestiae, voluptatum voluptatibus cum ad aliquam, labore incidunt earum vero fugit aperiam aliquid quaerat enim! Natus consequuntur, sit incidunt harum laudantium laboriosam ex eius illum omnis blanditiis necessitatibus totam nemo animi repudiandae ipsum voluptate reiciendis similique eveniet culpa numquam. Accusantium repellendus consequatur et amet numquam quidem quo alias, necessitatibus eveniet nemo voluptatibus consequuntur voluptatem odit magni pariatur soluta laboriosam hic aliquam deserunt tenetur sunt, non quas. Eaque veritatis deleniti nemo eos nesciunt vitae? Molestias ea possimus atque, nobis cupiditate ab. Laboriosam aut vel molestias deserunt voluptatem inventore placeat quas doloremque unde fugiat aliquam accusamus ducimus magnam beatae corrupti harum ipsa, atque iste, vero illo, quia consequuntur dolore odit! Dignissimos delectus voluptate, tenetur blanditiis voluptas laudantium optio exercitationem et minima nam maiores nemo consequatur rerum assumenda omnis vitae repudiandae impedit tempore corrupti! Perferendis minima, maxime sint dolores fuga magni possimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nihil iusto ipsum sequi soluta, magni debitis doloribus voluptatibus accusamus dolorum consequatur fugit, quaerat velit ab quia qui asperiores eius voluptates quisquam!",
        Perks:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur nisi dolore sequi corrupti ipsam beatae vero, magni numquam laborum aspernatur quis, eius ratione illo praesentium.",
        Speaker:["Marine Gwenddydd","Managing Director"],
        SpeakerDesc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas optio delectus velit earum qui, dicta excepturi voluptas beatae tenetur inventore harum recusandae, placeat minus dignissimos doloribus quo voluptate debitis consectetur vel reprehenderit molestiae. Optio omnis quis, ex, laudantium reiciendis eveniet officiis maiores aut error earum mollitia at perspiciatis sint soluta."
    },
    {
        ID:2,
        Name:"Brainwave Robotics Workshop 2",
        About:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis aperiam aut dolorem repellat cum totam architecto. Quo ipsum, excepturi voluptas debitis eos inventore fuga reiciendis illo asperiores quasi tenetur earum tempore placeat odit repellendus rerum eius. Eum veniam ipsum voluptate ea minima porro vitae numquam minus error delectus tenetur voluptatem nobis, doloribus inventore eos debitis eligendi dolorum obcaecati ipsam maxime! Ipsum molestiae, voluptatum voluptatibus cum ad aliquam, labore incidunt earum vero fugit aperiam aliquid quaerat enim! Natus consequuntur, sit incidunt harum laudantium laboriosam ex eius illum omnis blanditiis necessitatibus totam nemo animi repudiandae ipsum voluptate reiciendis similique eveniet culpa numquam. Accusantium repellendus consequatur et amet numquam quidem quo alias, necessitatibus eveniet nemo voluptatibus consequuntur voluptatem odit magni pariatur soluta laboriosam hic aliquam deserunt tenetur sunt, non quas. Eaque veritatis deleniti nemo eos nesciunt vitae? Molestias ea possimus atque, nobis cupiditate ab. Laboriosam aut vel molestias deserunt voluptatem inventore placeat quas doloremque unde fugiat aliquam accusamus ducimus magnam beatae corrupti harum ipsa, atque iste, vero illo, quia consequuntur dolore odit! Dignissimos delectus voluptate, tenetur blanditiis voluptas laudantium optio exercitationem et minima nam maiores nemo consequatur rerum assumenda omnis vitae repudiandae impedit tempore corrupti! Perferendis minima, maxime sint dolores fuga magni possimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nihil iusto ipsum sequi soluta, magni debitis doloribus voluptatibus accusamus dolorum consequatur fugit, quaerat velit ab quia qui asperiores eius voluptates quisquam!",
        Perks:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur nisi dolore sequi corrupti ipsam beatae vero, magni numquam laborum aspernatur quis, eius ratione illo praesentium.",
        Speaker:["Marine Gwenddydd","Managing Director"],
        SpeakerDesc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas optio delectus velit earum qui, dicta excepturi voluptas beatae tenetur inventore harum recusandae, placeat minus dignissimos doloribus quo voluptate debitis consectetur vel reprehenderit molestiae. Optio omnis quis, ex, laudantium reiciendis eveniet officiis maiores aut error earum mollitia at perspiciatis sint soluta."
    },
    {
        ID:3,
        Name:"Brainwave Robotics Workshop 3",
        About:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis aperiam aut dolorem repellat cum totam architecto. Quo ipsum, excepturi voluptas debitis eos inventore fuga reiciendis illo asperiores quasi tenetur earum tempore placeat odit repellendus rerum eius. Eum veniam ipsum voluptate ea minima porro vitae numquam minus error delectus tenetur voluptatem nobis, doloribus inventore eos debitis eligendi dolorum obcaecati ipsam maxime! Ipsum molestiae, voluptatum voluptatibus cum ad aliquam, labore incidunt earum vero fugit aperiam aliquid quaerat enim! Natus consequuntur, sit incidunt harum laudantium laboriosam ex eius illum omnis blanditiis necessitatibus totam nemo animi repudiandae ipsum voluptate reiciendis similique eveniet culpa numquam. Accusantium repellendus consequatur et amet numquam quidem quo alias, necessitatibus eveniet nemo voluptatibus consequuntur voluptatem odit magni pariatur soluta laboriosam hic aliquam deserunt tenetur sunt, non quas. Eaque veritatis deleniti nemo eos nesciunt vitae? Molestias ea possimus atque, nobis cupiditate ab. Laboriosam aut vel molestias deserunt voluptatem inventore placeat quas doloremque unde fugiat aliquam accusamus ducimus magnam beatae corrupti harum ipsa, atque iste, vero illo, quia consequuntur dolore odit! Dignissimos delectus voluptate, tenetur blanditiis voluptas laudantium optio exercitationem et minima nam maiores nemo consequatur rerum assumenda omnis vitae repudiandae impedit tempore corrupti! Perferendis minima, maxime sint dolores fuga magni possimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nihil iusto ipsum sequi soluta, magni debitis doloribus voluptatibus accusamus dolorum consequatur fugit, quaerat velit ab quia qui asperiores eius voluptates quisquam!",
        Perks:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur nisi dolore sequi corrupti ipsam beatae vero, magni numquam laborum aspernatur quis, eius ratione illo praesentium.",
        Speaker:["Marine Gwenddydd","Managing Director"],
        SpeakerDesc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas optio delectus velit earum qui, dicta excepturi voluptas beatae tenetur inventore harum recusandae, placeat minus dignissimos doloribus quo voluptate debitis consectetur vel reprehenderit molestiae. Optio omnis quis, ex, laudantium reiciendis eveniet officiis maiores aut error earum mollitia at perspiciatis sint soluta."
    },
    {
        ID:4,
        Name:"Brainwave Robotics Workshop 4",
        About:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis aperiam aut dolorem repellat cum totam architecto. Quo ipsum, excepturi voluptas debitis eos inventore fuga reiciendis illo asperiores quasi tenetur earum tempore placeat odit repellendus rerum eius. Eum veniam ipsum voluptate ea minima porro vitae numquam minus error delectus tenetur voluptatem nobis, doloribus inventore eos debitis eligendi dolorum obcaecati ipsam maxime! Ipsum molestiae, voluptatum voluptatibus cum ad aliquam, labore incidunt earum vero fugit aperiam aliquid quaerat enim! Natus consequuntur, sit incidunt harum laudantium laboriosam ex eius illum omnis blanditiis necessitatibus totam nemo animi repudiandae ipsum voluptate reiciendis similique eveniet culpa numquam. Accusantium repellendus consequatur et amet numquam quidem quo alias, necessitatibus eveniet nemo voluptatibus consequuntur voluptatem odit magni pariatur soluta laboriosam hic aliquam deserunt tenetur sunt, non quas. Eaque veritatis deleniti nemo eos nesciunt vitae? Molestias ea possimus atque, nobis cupiditate ab. Laboriosam aut vel molestias deserunt voluptatem inventore placeat quas doloremque unde fugiat aliquam accusamus ducimus magnam beatae corrupti harum ipsa, atque iste, vero illo, quia consequuntur dolore odit! Dignissimos delectus voluptate, tenetur blanditiis voluptas laudantium optio exercitationem et minima nam maiores nemo consequatur rerum assumenda omnis vitae repudiandae impedit tempore corrupti! Perferendis minima, maxime sint dolores fuga magni possimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nihil iusto ipsum sequi soluta, magni debitis doloribus voluptatibus accusamus dolorum consequatur fugit, quaerat velit ab quia qui asperiores eius voluptates quisquam!",
        Perks:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur nisi dolore sequi corrupti ipsam beatae vero, magni numquam laborum aspernatur quis, eius ratione illo praesentium.",
        Speaker:["Marine Gwenddydd","Managing Director"],
        SpeakerDesc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas optio delectus velit earum qui, dicta excepturi voluptas beatae tenetur inventore harum recusandae, placeat minus dignissimos doloribus quo voluptate debitis consectetur vel reprehenderit molestiae. Optio omnis quis, ex, laudantium reiciendis eveniet officiis maiores aut error earum mollitia at perspiciatis sint soluta."
    },
    {
        ID:5,
        Name:"Brainwave Robotics Workshop 5",
        About:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis aperiam aut dolorem repellat cum totam architecto. Quo ipsum, excepturi voluptas debitis eos inventore fuga reiciendis illo asperiores quasi tenetur earum tempore placeat odit repellendus rerum eius. Eum veniam ipsum voluptate ea minima porro vitae numquam minus error delectus tenetur voluptatem nobis, doloribus inventore eos debitis eligendi dolorum obcaecati ipsam maxime! Ipsum molestiae, voluptatum voluptatibus cum ad aliquam, labore incidunt earum vero fugit aperiam aliquid quaerat enim! Natus consequuntur, sit incidunt harum laudantium laboriosam ex eius illum omnis blanditiis necessitatibus totam nemo animi repudiandae ipsum voluptate reiciendis similique eveniet culpa numquam. Accusantium repellendus consequatur et amet numquam quidem quo alias, necessitatibus eveniet nemo voluptatibus consequuntur voluptatem odit magni pariatur soluta laboriosam hic aliquam deserunt tenetur sunt, non quas. Eaque veritatis deleniti nemo eos nesciunt vitae? Molestias ea possimus atque, nobis cupiditate ab. Laboriosam aut vel molestias deserunt voluptatem inventore placeat quas doloremque unde fugiat aliquam accusamus ducimus magnam beatae corrupti harum ipsa, atque iste, vero illo, quia consequuntur dolore odit! Dignissimos delectus voluptate, tenetur blanditiis voluptas laudantium optio exercitationem et minima nam maiores nemo consequatur rerum assumenda omnis vitae repudiandae impedit tempore corrupti! Perferendis minima, maxime sint dolores fuga magni possimus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nihil iusto ipsum sequi soluta, magni debitis doloribus voluptatibus accusamus dolorum consequatur fugit, quaerat velit ab quia qui asperiores eius voluptates quisquam!",
        Perks:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur nisi dolore sequi corrupti ipsam beatae vero, magni numquam laborum aspernatur quis, eius ratione illo praesentium.",
        Speaker:["Marine Gwenddydd","Managing Director"],
        SpeakerDesc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas optio delectus velit earum qui, dicta excepturi voluptas beatae tenetur inventore harum recusandae, placeat minus dignissimos doloribus quo voluptate debitis consectetur vel reprehenderit molestiae. Optio omnis quis, ex, laudantium reiciendis eveniet officiis maiores aut error earum mollitia at perspiciatis sint soluta."
    }
]

export default WorkshopContent